[tool.black]
target-version = ["py39"]
line-length = 120

[tool.isort]
profile = "black"
skip = "venv"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120

[tool.mypy]
plugins = ["pydantic.mypy"]
pretty = true
show_error_codes = true
color_output = true

exclude = [".venv"]

strict = true
check_untyped_defs = true
disallow_untyped_defs = false
disallow_incomplete_defs = false
disallow_untyped_calls = false
warn_return_any = false
disallow_untyped_decorators = false  # TODO: Fix this later

[tool.pytest.ini_options]
addopts = "-p no:cacheprovider"
