name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@v8
        with:
          python-version: "3.14"
          enable-cache: true

      - run: uv sync --frozen

      - run: make check-types
      - run: make lint
      - run: make check-format

      - run: make test
      - run: make test-integration
      - run: make test-end-to-end

      - run: make seed
