name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11.9

      - run: make install

      - run: make check-types
      - run: make check-flake8
      - run: make check-isort
      - run: make check-black

      - run: make test
      - run: make test-integration
      - run: make test-end-to-end

      - run: make seed
